# Generated by Django 2.0.1 on 2019-01-29 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_product', models.CharField(max_length=50, verbose_name='Название')),
                ('desc_product', models.TextField(verbose_name='Описание')),
                ('img_product', models.ImageField(blank=True, default='', upload_to='productpage/image', verbose_name='логотип')),
            ],
            options={
                'verbose_name': 'Продукты и сервисы',
                'verbose_name_plural': 'Продукты',
            },
        ),
    ]
