# Generated by Django 2.0.1 on 2019-01-27 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio_team', models.CharField(max_length=50, verbose_name='Имя и фамилия')),
                ('work_team', models.CharField(max_length=50, verbose_name='Должность')),
                ('vk_team', models.URLField(verbose_name='Ссылка Вконтакте')),
                ('fb_team', models.URLField(verbose_name='Ссылка Facebook')),
                ('tw_team', models.URLField(verbose_name='Ссылка Twitter')),
                ('photo_team', models.ImageField(blank=True, default='', upload_to='teampage/photo', verbose_name='Фотография')),
            ],
            options={
                'verbose_name': 'Команда.Кто мы?',
                'verbose_name_plural': 'команда',
            },
        ),
    ]
