# Generated by Django 2.0.1 on 2019-01-22 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headingh1', models.CharField(max_length=50, verbose_name='Заголовок h1')),
                ('headingh2', models.CharField(max_length=80, verbose_name='Заголовок h2')),
                ('description', models.TextField(verbose_name='описание')),
                ('vk_social', models.URLField(verbose_name='Ссылка Вконтакте')),
                ('fb_social', models.URLField(verbose_name='Ссылка Facebook')),
                ('tw_social', models.URLField(verbose_name='Ссылка Twitter')),
                ('phone', models.CharField(max_length=30, verbose_name='Телефон')),
            ],
        ),
    ]
