# Generated by Django 2.0.1 on 2019-01-22 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='main',
            options={'verbose_name': 'главная', 'verbose_name_plural': 'главная'},
        ),
    ]
