# Generated by Django 2.0.1 on 2019-01-24 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0002_auto_20190122_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='logoimg',
            field=models.ImageField(blank=True, default='', upload_to='mainpage/logo', verbose_name='логотип'),
        ),
    ]
