# Generated by Django 2.0.1 on 2019-01-27 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descpromo', models.TextField(verbose_name='Текст акции')),
                ('imgpromo', models.ImageField(blank=True, default='', upload_to='promopage/image', verbose_name='логотип')),
            ],
            options={
                'verbose_name': 'акции',
                'verbose_name_plural': 'акции',
            },
        ),
    ]
